plugins: ["prettier-plugin-solidity"]
arrowParens: "avoid"
bracketSpacing: true
endOfLine: "auto"
printWidth: 100
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: ["*.sol", "*.t.sol"]
    options:
      tabWidth: 4
      parser: "solidity-parse"
